version: '3.9'
services:
  app:
    container_name: ${CONTAINER_PREFIX}_jupyterlab
    image: template_data_analysis  # Specifies the name for the built image.
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    command:
      - "jupyter"
      - "lab"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"
      - "--allow-root"
      - "--NotebookApp.token=''"
      - "--NotebookApp.notebook_dir='/app'"      
  mongodb:
    image: mongo:7
    container_name: ${CONTAINER_PREFIX}_mongodb
    restart: always
    ports:
      - 27017:27017