-- EMPLOYEE 테이블
CREATE TABLE `EMPLOYEE` (
    `EMP_ID` VARCHAR(20) PRIMARY KEY,
    `EMP_NAME` VARCHAR(50),
    `DEPT_ID` VARCHAR(20),  -- 부서 외래키
    CONSTRAINT `FK_EMPLOYEE_DEPARTMENT` FOREIGN KEY (`DEPT_ID`) REFERENCES `DEPARTMENT`(`DEPT_ID_PK`)
);

-- DEPARTMENT 테이블
CREATE TABLE `DEPARTMENT` (
    `DEPT_ID_PK` VARCHAR(20) PRIMARY KEY,
    `DEPT_NAME` VARCHAR(50)
);

-- ATTENDANCE 테이블
CREATE TABLE `ATTENDANCE` (
    `ATD_ID_PK` VARCHAR(20) PRIMARY KEY,
    `EMP_ID` VARCHAR(20),  -- 직원 외래키
    `DATE` VARCHAR(20),  -- 날짜
    `ATD_TYPE_PK` VARCHAR(20),  -- 근태 유형 외래키
    `DEPT_ID` VARCHAR(20),  -- 부서 외래키
    CONSTRAINT `FK_ATTENDANCE_EMPLOYEE` FOREIGN KEY (`EMP_ID`) REFERENCES `EMPLOYEE`(`EMP_ID`),
    CONSTRAINT `FK_ATTENDANCE_DEPARTMENT` FOREIGN KEY (`DEPT_ID`) REFERENCES `DEPARTMENT`(`DEPT_ID_PK`),
    CONSTRAINT `FK_ATTENDANCE_ATTENDTYPE` FOREIGN KEY (`ATD_TYPE_PK`) REFERENCES `ATTENDTYPE`(`ATD_TYPE_PK`)
);

-- ATTENDTYPE 테이블
CREATE TABLE `ATTENDTYPE` (
    `ATD_TYPE_PK` VARCHAR(20) PRIMARY KEY,
    `ATD_TYPE` VARCHAR(20)
);
